version: "3.6"

services:

  server:
    image: aeternity/governance-server
    restart: unless-stopped
    ports:
      - 3000:3000
    links:
      - aeternity_proxy
      - redis
      - middleware
      - compiler
    environment:
      - CONTRACT_ADDRESS=ct_2cFxfeheJGfy4cwBWmeJ2wiiRM9BvJh6cCevdsoGv2VNascjsc
      - NODE_URL=http://aeternity_proxy:3013/
      - COMPILER_URL=http://compiler:3080
      - WEBSOCKET_URL=ws://middleware:3020
      - REDIS_URL=redis://redis:6379

  aeternity:
    image: aeternity/aeternity:v4.2.0
    restart: unless-stopped
    hostname: aeternity
    volumes:
      - ./aeternity.yaml:/home/aeternity/.aeternity/aeternity/aeternity.yaml
      - aeternity_data:/home/aeternity/node/data/mnesia
    ports:
      - 3013:3013
      
  compiler:
    image: aeternity/aesophia_http:v3.2.0
    restart: unless-stopped
    hostname: compiler

  aeternity_proxy:
    image: nginx:1.13.8
    restart: unless-stopped
    hostname: aeternity_proxy
    links:
      - aeternity
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    logging:
      driver: none

  middleware_db:
    image: postgres:11
    restart: unless-stopped
    environment:
      - POSTGRES_USER=middleware
      - POSTGRES_PASSWORD=middleware
      - POSTGRES_DB=middleware
    volumes:
      - middleware_db_data:/var/lib/postgresql/data

  middleware:
    image: aeternity/aepp-middleware
    restart: unless-stopped
    hostname: middleware
    entrypoint: ./aepp-middleware -p -s -w
    environment:
      - RUST_BACKTRACE=full
      - RUST_LOG=mdw
      - NODE_URL=http://aeternity_proxy:3013
      - DATABASE_URL=postgres://middleware:middleware@middleware_db/middleware
    depends_on:
      - aeternity
    links:
      - aeternity_proxy
      - middleware_db
    ports:
      - 3020:3020
      - 8000:80

  redis:
    image: redis
    restart: unless-stopped
    hostname: redis

volumes:
  aeternity_data:
  middleware_db_data:

